<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="TailEndianSwap" Id="{b83d4834-125c-4a8f-ba5a-f0b762aa00d5}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION TailEndianSwap : EspUdpEnd
VAR_INPUT
	In	: EspUdpEnd;
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[In.EndDelimiter			:= BE16_TO_HOST(In.EndDelimiter);

TailEndianSwap := In;
]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>